#!/bin/bash
HW='COD-Lab/fpga/design/ucas-cod/hardware/sources'
SW='COD-Lab/software/workload/ucas-cod/benchmark/simple_test'



# update COD-Lab
cd COD-Lab && git pull && cd .. || exit 1
git add COD-Lab



# hardware
rm -r hardware
cp -r $HW hardware
# dma: remove private information
sed -i "2,21d" hardware/custom_cpu/dma/engine_core.v
sed -i "1,9d" hardware/custom_cpu/dma/dma_engine.v
# simple_cpu: add single_cycle & multi_cycle
mkdir hardware/simple_cpu/single_cycle
mv hardware/simple_cpu/simple_cpu.v hardware/simple_cpu/single_cycle
cd COD-Lab && git checkout simple_cpu-multi_cycle && cd ..
mkdir hardware/simple_cpu/multi_cycle
cp $HW/simple_cpu/simple_cpu.v hardware/simple_cpu/multi_cycle
cd COD-Lab && git checkout master && cd ..

git add hardware/



# software
rm -r software
mkdir software
mkdir software/common
cp -r $SW/common/perf_cnt.c $SW/common/printf.c software/common/

mkdir software/microbench
cp -r $SW/microbench/bench.c software/microbench/

mkdir software/dnn_test
cp -r $SW/dnn_test/src/conv.c software/dnn_test/

mkdir software/dma_test
cp -r $SW/dma_test/mips/common/intr_handler.S software/dma_test/

mkdir software/include
cp -r $SW/include/perf_cnt.h software/include/

git add software/
