#!/bin/bash
HW='COD-Lab/fpga/design/ucas-cod/hardware/sources'
SW='COD-Lab/software/workload/ucas-cod/benchmark/simple_test'

cd COD-Lab && git pull && cd .. || exit 1
git add COD-Lab

rm -r hardware
mkdir hardware
cp -r $HW/alu $HW/example $HW/reg_file $HW/shifter $HW/simple_cpu hardware/
mkdir hardware/custom_cpu
cp -r $HW/custom_cpu/mips $HW/custom_cpu/riscv32 hardware/custom_cpu
git add hardware/

rm -r software
mkdir software
mkdir software/common
cp -r $SW/common/*.c software/common/
mkdir software/microbench
cp -r $SW/microbench/*.c software/microbench/
mkdir software/include
cp -r $SW/include/perf_cnt.h software/include/
git add software/
